# Generated by Django 4.2.5 on 2023-10-08 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_tag_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
